# Dockerfile para la API de FastAPI
FROM python:3.11

WORKDIR /app

# Instalar dependencias
COPY ./requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el código fuente
# Copia todo el contenido del contexto (la carpeta 'backend') a /app
COPY . .

# Exponer el puerto y ejecutar la aplicación
EXPOSE 8000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
